### PR TITLE
update for dictionary

### PR DESCRIPTION
**Pull request by XXN**
+few translations;
deactivated bad/incomplete Belarusian terms for 'Wikimedia category';
*ref for 'ta':species of insect=பூச்சி இனம் - diff=495313198 (mass addition)

### CODE REVIEW

**Comment by emijrp** [comment]
Thanks! Could you provide the right be: & be-tarask: translations for "Wikimedia category"? So, bot can fix them in the next run.

**Comment by XXN** [comment]
Since I am not a speaker of Belarusian and I am not sure at 100% in the translations I can provide, I've asked a native speaker ('Special:diff/500815051') and I hope he will answer soon. However this is not my first attept, previously I've asked someone else also, but since the needed answer/action was missing, for the moment it was a good step to disable bad translations, though I agree, it's better to have them corrected directly.

**Comment by XXN** [comment]
Meanwhile I received an answer (diff=500816322); thanks goes to EugeneZelenko. I will update the patch right now.

**Comment by XXN** [comment]
@emijrp, seems that [these](https://github.com/emijrp/wikidata/pull/27/commits/29c0cba0c427564f60daf9a4305161b40b9e4389) Belarusian translations were lost due to a new paralel 'conflicting' patch. You may want to re-add them manually.

**Comment by XXN** [comment]
If you have some free time you can compare also your dictionaries with the ones from https://www.wikidata.org/wiki/MediaWiki:Gadget-autoEdit.js - you could find some missing entries to be added,

**Comment by emijrp** [comment]
> @emijrp, seems that these Belarusian translations were lost due to a new paralel 'conflicting' patch. You may want to re-add them manually.

@XXN I see them here https://github.com/emijrp/wikidata/blob/master/common.descriptions.py#L597

**Comment by XXN** [comment]
You are right. Sorry. A link above (automatic [52d1c57](https://github.com/emijrp/wikidata/commit/52d1c57bdf6f272f52042e0513830a22f4ec34fe) commit merge message) confused me...

**Pull request merged**
