### PR TITLE
Update human.descriptions.py

### PR DESCRIPTION
**Pull request by BABZAA**
Hello! I translate them?. Greetings

### CODE REVIEW

**Comment by emijrp** [comment]
Thanks!

**Comment by emijrp** [comment]
In "association football manager" did you put "basketball"?

**Comment by emijrp** [comment]
In films script, directors are written in Latin chars. So for Arabic descriptions would be better to use just the ~YEAR~ variable, as in Hebrew translation. Could you fix that? I can't edit Arabic correctly to remove the after comma half sentence.

**Comment by BABZAA** [comment]
Yes, sorry for this error, so I'm all I've Reviewed. for "films script" I think that too.

**Comment by emijrp** [comment]
So, can you update your repo, and fix that two issues?

**Pull request merged**
