### PR TITLE
Update human.descriptions.py

### PR DESCRIPTION
**Pull request by BABZAA**
Hello! I made a spelling mistake in Arabic, in the "comics artist" and "politician" and "businessperson" in the descriptions of female, please restart your bot for add descriptions in Arabic, after this update.

### CODE REVIEW

**Comment by emijrp** [comment]
The branch has conflicts and I don't know how to solve, because the involved text is in Arabic and I don't know what to choose.

Please, update your fork, and re-make your changes and pullrequest again.

**Comment by BABZAA** [comment]
like this!
         '~ politician': {
            'ar': { 'male': 'سياسي ~', 'female': 'سياسية ~' }, 
-------------------------
        '~ comics artist': {
            'ar': { 'male': 'فنان قصص مصورة ~', 'female': 'فنانة قصص مصورة ~' },
-------------------------
        '~ businessperson': {
           'ar': { 'male': 'رجل أعمال ~', 'female': 'سيدة أعمال ~' },

**Comment by emijrp** [comment]
OK! I have fixed that 3 translations here 94545cd43ced50c1cdce01babcdee7de5b55be77

Can you check how many Arabic human descriptions are wrong? If you know how to use WDQS https://query.wikidata.org and FILTER(CONTAINS()) I think we could get all the errors.

I will keep the human description bot stopped for some days until we fix all the errors.

Please, double check all the Arabic translations in the code when you can.

**Comment by emijrp** [comment]
Here is an example query. 52 errors for businesspeople female

https://query.wikidata.org/#SELECT%20%3Fitem%20%3Fardesc%0AWHERE%20%7B%0A%09%3Fitem%20wdt%3AP31%20wd%3AQ5.%0A%20%20%20%20%3Fitem%20wdt%3AP21%20wd%3AQ6581072.%0A%20%20%20%20%3Fitem%20wdt%3AP106%20wd%3AQ43845.%0A%20%20%20%20%3Fitem%20schema%3Adescription%20%3Fardesc.%20FILTER%28LANG%28%3Fardesc%29%20%3D%20%22ar%22%29.%0A%20%20%20%20FILTER%20CONTAINS%28%3Fardesc%2C%20%22%D8%B1%D8%AC%D9%84%20%D8%A3%D8%B9%D9%85%D8%A7%D9%84%22%29.%0A%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%7D%0A%7D

Not many. Can you fix them by hand or using quickstatements? Be careful nationalities are different.

**Comment by BABZAA** [comment]
Yes, I'll do it, thank you very much.

**Comment by BABZAA** [comment]
Please, Fix description female of ¨Russian¨, like this!
        'Russian': {
            'ar': { 'male': 'روسي', 'female': 'روسية' },

**Comment by emijrp** [comment]
Hello @BABZAA Did you fix the errors in Wikidata?

**Comment by BABZAA** [comment]
Hello. Yes, in 21 March 2017. [https://www.wikidata.org/w/index.php?title=Q6259288&type=revision&diff=469168176&oldid=469078100](url)

**Pull request merged**
