### PR TITLE
Update film.descriptions.py

### PR DESCRIPTION
**Pull request by mikey641**
hebrew translations

### CODE REVIEW

**Comment by emijrp** [comment]
Thanks again!

**Comment by emijrp** [comment]
Just a notice. By now the script uses the English name for directors, so it would mix Latin and Hebrew characters in the Hebrew descriptions, and I think that it is wrong. I think I will exclude he: until I think a solution.

**Comment by mikey641** [comment]
hey. maybe until you find a solution you can just add the description 
        'he': 'סרט משנת ~YEAR~',

**Comment by emijrp** [comment]
That is a smart solution. I'm going to add it.

**Pull request merged**
