### PR TITLE
Add Indonesian translations

### PR DESCRIPTION
**Pull request by Rachmat04**
Hello,

I'd like to propose some translations from Bahasa Indonesia to be merged to master repository. Any feedback and modifications are welcome.

Thanks.

### CODE REVIEW

**Comment by emijrp** [comment]
@Rachmat04 Thanks for your PR, though I think you have to do some changes.

In "fixthiswhenfound" dictionary you must add only WRONG translations, not right ones.

For example, if "desa di Cina" is wrong, you add it to "fixthiswhenfound". And in "translations" you add "desa di Tiongkok" which is the right one.

**Comment by Rachmat04** [comment]
Thanks for the feedback.
I'll do some fixes right away.

**Comment by emijrp** [comment]
I think that now it is correct.

**Comment by Rachmat04** [comment]
@emijrp Thank you! 😃

**Pull request merged**
