### PR TITLE
Update human.descriptions.py

### PR DESCRIPTION
**Pull request by ldons**
Added Albanian (sq) translation.

### CODE REVIEW

**Comment by emijrp** [comment]
Hello! Thanks a lot for your work.

I have found some details I want to discuss:

* Rwandan nationality is missing
* In some occupations, ~ is in the middle, is that the correct place for nationalities? Example: 'historian ~ i artit'. Sometimes is in the end 'menaxher futbolli ~'
* Rabbi occupation is commented #, is that a mistake?

I will merge soon. But I will wait some days before running the bot. Experience tells me you could find some errors in the nationalities translations.

**Comment by ldons** [comment]
1. I couldn't translate them all, and maybe 30-40% of translations aren't finished.
2. "~" in middle is ok, that is how we use in Albanian, because in those cases if nationality is in the end then it changes the meaning of description
3. My mistake to comment that, Rabbi is translated ok.

Yes, there can be mistakes. Then is Ok, reject/delete this commit, next weekend I will complete it and will submit again.

**Comment by emijrp** [comment]
I will keep this pull-request open. Take your time to add more changes.

**Comment by ldons** [comment]
@emijrp added more translations, and fixed some mistakes that initial pull had.

**Comment by emijrp** [comment]
Thanks for your new changes.

How many translations are remaining? Should I merge?

**Comment by ldons** [comment]
There are some nationalities for which I cant find proper translation. If it is not a problem, merge it for now. I will try to find translation for this and other scripts.

**Comment by emijrp** [comment]
OK, merging.

**Pull request merged**
