### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by mikey641**

### CODE REVIEW

**Comment by emijrp** [comment]
Great work. Excellent.

Is there a List of demonyms in Hebrew Wikipedia?[1]

[1] https://en.wikipedia.org/wiki/List_of_adjectival_and_demonymic_forms_for_countries_and_nations

**Comment by mikey641** [comment]
Thanks.  Unfortunately there is no List of demonyms in Hebrew Wikipedia because in hewiki there are no list articles. I added most of these on my own and when I wasn't sure about the demonym I went to [קטגוריה:עמים](https://he.wikipedia.org/wiki/%D7%A7%D7%98%D7%92%D7%95%D7%A8%D7%99%D7%94:%D7%A2%D7%9E%D7%99%D7%9D) in which the demonym is written in plural or looked in articles.

**Comment by emijrp** [comment]
@mikey641 you forgot to translate:
* Beninese (Benin), Beninois (Benin alternative form)
* Bruneian (Brunei)
* Lao (Laos), Laotian (Laos alternative form)
* Sammarinese (San Marino)
* São Toméan (São Tomé and Príncipe)

If there aren't known demonyms for these, you can add them like "[person] of Benin", like for Emirati case.

I have updated the repo, update your fork.

**Comment by mikey641** [comment]
I didn't actually forget it. I just didn't know how to write the demonyms so I asked how to write it in [the hebrew Reference desk/Language](https://he.wikipedia.org/wiki/%D7%95%D7%99%D7%A7%D7%99%D7%A4%D7%93%D7%99%D7%94:%D7%99%D7%99%D7%A2%D7%95%D7%A5_%D7%9C%D7%A9%D7%95%D7%A0%D7%99)
I'm gonna add "[person] of Benin", until I get an answer

**Comment by mikey641** [comment]
just updated

**Comment by emijrp** [comment]
Perfect

**Comment by mikey641** [comment]
Just a question. Does your bot update descriptions? for example if the english description is "actor" but the hebrew is "singer" would it change the hebrew to "actor"?

**Comment by emijrp** [comment]
Nope. The script doen't overwrite any field. It only fills blank fields. Are there many errors in Hebrew descriptions or what?

I want to create a script to fix common errors by the way. I have seen some bots added wrong descriptions in Spanish (male descriptions in female items for example).

**Comment by emijrp** [comment]
Bot is adding the he: translations. Take a look and tell me if you see something wrong.

**Comment by mikey641** [comment]
This is so cool. From what I see it's great. And yes. There are many errors (thanks to me) I added many descriptions using [a tool called descriptioner](http://tools.wmflabs.org/pltools/descriptioner/) using SPARQL and if someone is a singer and an actor, but mostly an actor, some times it would that he's just a singer.

**Pull request merged**
